spring:
  application:
    name: Basilisk Basic Application

management:
  tracing:
    sampling:
      probability: 1.0
signal:
  action: forward
  response: NA

tracing:
  url: http://localhost:4318/v1/traces

downstream:
  url: http://localhost:8085
  path: checkSignal

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
